name = "getv"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "getv.226022.xyz/*"
zone_name = "226022.xyz"

[vars]
ENVIRONMENT = "production"
